version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: school-vaccination-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - school-vaccination-network

networks:
  school-vaccination-network:
    driver: bridge 